
services:
  service1:
    build: ./service1
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker


  service2:
    build: ./service2
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - service1