
services:
  service1:
    build: ./service1
    image: service1:latest
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker


  service2:
    build: ./service2
    image: service2:latest
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - service1